### PR TITLE
ASM6 initialization

### PR DESCRIPTION
**Pull request by batmat**
The gist of this PR is the use of `6.0_BETA` released a few weeks ago. 

@reviewbybees esp. @kohsuke @markewaite

### CODE REVIEW

**Comment by batmat** [comment]
@kohsuke if you're fine with this, and end up merging it, it would be great if you can also release the corresponding beta versio so that we can start using it where it needs to, to see what the next stop is (I already fixed BCT with a SNAPSHOT of this, for instance, so I'd file a followup for this as soon as you do the release).

Thanks!

**Comment by kohsuke** [comment]
It turns out without javadoc jar the maven central doesn't accept it.

**Comment by kohsuke** [comment]
Reverted 5aad359a0566ded7161e4dcb440486f5ffcc1371 and released 6.0_BETA

**Comment by batmat** [comment]
Thanks, and sorry for the the Javadoc mishaps. I assumed wrongly that the sources would be enough.

**Pull request merged**
